### ISSUE TITLE
Clicked blue star icon on image component, nothing happen

### ISSUE THREAD

**Issue by indianajava** [linb/CrossUI#43] opened 2020-08-24 09:53 UTC
![image](https://user-images.githubusercontent.com/50699924/91030734-d16f4780-e629-11ea-816c-ec5bb8efddd4.png)

**Comment by linb** [comment] 2020-08-24 13:43
Fixed in online version

**Closed by linb** 2020-08-24 13:43 UTC

**Comment by indianajava** [comment] 2020-08-24 15:14
still error while fetching image from image selector dialog.

**Comment by linb** [comment] 2020-08-24 17:35
Oh, it's an error caused by TreeGrid modification.
Fixed it. Try it again please!

**Comment by indianajava** [comment] 2020-08-24 23:19
it worked. thks
